### ISSUE TITLE
grab_beacon_config: ERROR: Script execution failed (use -d to debug)

### ISSUE THREAD

**Issue by NickYan7** [whickey-r7/grab_beacon_config#1]
Is this a bug or I use it wrong? Please check it out, thanks a lot!
![Screenshot 2020-12-03 下午6 46 55](https://user-images.githubusercontent.com/27906343/100999617-f152c780-3597-11eb-9327-f729afa45091.jpg)
![Screenshot 2020-12-03 下午6 46 11](https://user-images.githubusercontent.com/27906343/100999626-f44db800-3597-11eb-9f40-f3eab0c4203d.jpg)

**Comment by oilflashy** [comment]
I also encountered this issue while using this script.  The value of response.rawbody was 'nil' in every I tested.  I was able to successfully run the script by subbing 'response.body' for 'response.rawbody'.

**Comment by whickey-r7** [comment]
Error checking has been added. This should be resolved.
